builds:
    - binary: mapcidr
      main: cmd/mapcidr/main.go
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - 386
        - arm
        - arm64
  
archives:
    - id: tgz
      format: tar.gz
      replacements:
          darwin: macOS
      format_overrides:
          - goos: windows
            format: zip

snapcrafts:
  - id: mapcidrx
    replacements:
      darwin: macOS
    name: mapcidrx
    publish: true
    summary: Utility to perform multiple operations for a given subnet/CIDR ranges
    description: |
      A utility program to perform multiple operations for a given subnet/cidr ranges. 
      mapCIDR is developed to ease load distribution for mass scanning operations,
      it can be used both as a library and as independent CLI tool.
    grade: stable
    confinement: devmode # strict
    license: MIT
    base: core18
    apps:
      mapcidr:
        command: mapcidr
        plugs:
          - home
          - network
          - removable-media
          # - dot-mapcidr

    # plugs:
    #   dot-mapcidr:
    #     interface: personal-files
    #     write:
    #       - $HOME/.config/mapcidr

