name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Check out code"
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with: 
          go-version: 1.16
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
      - env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v2
        with: 
          args: "release --rm-dist --parallelism=1"
          version: latest
          workdir: .