name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Check out code"
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with: 
          go-version: 1.16
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v2
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with: 
          args: "release --rm-dist --parallelism=1"
          version: latest
          workdir: .