name: Snap
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with: 
          go-version: 1.16
      - name: Setup Snapcraft
        run: |
          sudo snap install snapcraft --classic
          echo "$SNAP_TOKEN" | snapcraft login --with -
          snapcraft
          snapcraft upload --release=stable *.snap        
        env:
          SNAP_TOKEN: ${{secrets.SNAP_TOKEN}} 
          SNAPCRAFT_BUILD_ENVIRONMENT: host